title: jquery.utils
version: 0.5
dest: dist/
modules:
  - file: src/jquery.utils.js
    depends:
      - from: src/jquery.utils.js
      - from: src/jquery.anchorHandler.js
      - from: src/jquery.cookie.js
      - from: src/jquery.countdown.js
      - from: src/jquery.cycle.js
      - from: src/jquery.delayedObserver.js
      - from: src/jquery.flash.js
      - from: src/jquery.i18n.js
      - from: src/jquery.ifixpng.js
      - from: src/jquery.mousewheel.js
      - from: src/jquery.strings.js
      - from: src/jquery.timeago.js
      - from: src/jquery.youtubeLinksToEmbed.js

  - file: src/jquery.utils.js
    title: jquery.utils.min
    destfile: jquery.utils.ui.js
    depends:
      - from: src/jquery.utils.js
      - from: src/jquery.anchorHandler.js
      - from: src/jquery.cookie.js
      - from: src/jquery.countdown.js
      - from: src/jquery.cycle.js
      - from: src/jquery.delayedObserver.js
      - from: src/jquery.flash.js
      - from: src/jquery.i18n.js
      - from: src/jquery.ifixpng.js
      - from: src/jquery.mousewheel.js
      - from: src/jquery.strings.js
      - from: src/jquery.timeago.js
      - from: src/jquery.youtubeLinksToEmbed.js
      - from: src/ui.toaster.js
      - from: src/ui.masked.js
