title: jquery.djangoForm
version: 0.0.1
svnrev: true
dest: standalone/ui-djangoForm/dist/
modules:
  - file: standalone/ui-djangoForm/src/ui.djangoForm.js
    name: "djangoForm"
    destfile: ui.djangoForm.js
    depends:
      # src: src/jquery.utils.js
      - src: src/jquery.strings.js
      # src: src/jquery.delayedObserver.js

copy: 
  - src: demo/themes/default/images/*.png
    dest: standalone/ui-djangoForm/dist/themes/default/images/
  - src: demo/themes/default/*.css
    dest: standalone/ui-djangoForm/dist/themes/default/
  - src: standalone/ui-djangoForm/src/img/*
    dest: standalone/ui-djangoForm/dist/themes/default/images/
  # src: src/jquery.ui.all.js
  # dest: standalone/ui-djangoForm/src/jquery.ui.all.js
  # src: src/jquery.utils.js
  # dest: standalone/ui-djangoForm/src/jquery.utils.js
  - src: src/jquery.strings.js
    dest: standalone/ui-djangoForm/src/jquery.strings.js
  - src: src/jquery.strings.js
    dest: standalone/ui-djangoForm/testproject/media/js/jquery.strings.js
  - src: src/jquery.utils.js
    dest: standalone/ui-djangoForm/testproject/media/js/jquery.utils.js
# - src: standalone/ui-djangoForm/src/ui.djangoForm.js
#   dest: standalone/ui-djangoForm/testproject/media/js/ui.djangoForm.js
  - src: standalone/ui-djangoForm/testproject/media/js/ui.djangoForm.js
    dest: standalone/ui-djangoForm/src/ui.djangoForm.js

merge:
  - dest: standalone/ui-djangoForm/dist/themes/default/ui.djangoForm.css
    files:
      - src: standalone/ui-djangoForm/src/css/ui.djangoForm.css
zip:
  - dest: standalone/ui-djangoForm/downloads/ui.djangoForm-%v-standalone.zip
    src: standalone/ui-djangoForm/
    exclude: [".svn", "downloads", "build.yml", "demo"]

gzip:
  - dest: standalone/ui-djangoForm/downloads/ui.djangoForm-%v-standalone.tar.gz
    src: standalone/ui-djangoForm/
    exclude: [".svn", "downloads", "build.yml", "demo"]

