title: jquery.timepickr
version: 0.6.5
svnrev: true
dest: standalone/ui-timepickr/dist/
modules:
  - file: src/ui.timepickr.js
    name: "timepickr"
    destfile: jquery.timepickr.js
    depends:
      - src: src/jquery.utils.js
      - src: src/jquery.strings.js
      - src: src/jquery.arrayUtils.js
      # src: src/jquery.i18n.js
      - src: src/ui.dropslide.js

copy: 
  - src: demo/themes/default/images/*.png
    dest: standalone/ui-timepickr/dist/themes/default/images/
  - src: demo/themes/default/*.css
    dest: standalone/ui-timepickr/dist/themes/default/
  - dest: standalone/ui-timepickr/page/jquery.ui.all.js
    src: src/jquery.ui.all.js

merge:
  - dest: standalone/ui-timepickr/dist/themes/default/ui.timepickr.css
    files:
      - src: src/css/ui.dropslide.css
      - src: src/css/ui.timepickr.css
zip:
  - dest: standalone/ui-timepickr/downloads/jquery.timepickr-%v-standalone.zip
    src: standalone/ui-timepickr/
    exclude: [".svn", "downloads", "build.yml", "demo"]

gzip:
  - dest: standalone/ui-timepickr/downloads/jquery.timepickr-%v-standalone.tar.gz
    src: standalone/ui-timepickr/
    exclude: [".svn", "downloads", "build.yml", "demo"]

