title: jquery.timepickr
version: 0.1
svnrev: true
dest: dist/
modules:
  - file: ../../src/ui.timepickr.js
    destfile: jquery.timepickr.js
    depends:
      - src: ../../src/jquery.utils.js
      - src: ../../src/jquery.ui.all.js
      - src: ../../src/jquery.strings.js
      - src: ../../src/jquery.i18n.js
      - src: ../../src/ui.dropslide.js
merge:
  - dest: dist/ui.timepikr.css
    files:
      - src: ../../src/css/ui.dropslide.css
      - src: ../../src/css/ui.timepickr.css

